// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entity;

public partial class Advertisement
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int CreatorId { get; set; }

    public string FreeTxt { get; set; }

    public byte Status { get; set; }

    public int TimesViewed { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public virtual ICollection<AdvertismentProfessionalBranch> AdvertismentProfessionalBranches { get; set; } = new List<AdvertismentProfessionalBranch>();

    public virtual User Creator { get; set; }
}