// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entity;

public partial class AdvertismentWorkingLocation
{
    public int Id { get; set; }

    public int WorkingLocationId { get; set; }

    public int AdvertisementId { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public virtual Advertisement WorkingLocation { get; set; }

    public virtual RfdtWorkingLocation WorkingLocationNavigation { get; set; }
}