// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entity;

public partial class Chat
{
    public int Id { get; set; }

    public int UserId1 { get; set; }

    public int UserId2 { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual User UserId1Navigation { get; set; }

    public virtual User UserId2Navigation { get; set; }
}