// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace LinkiedInWebApi.Domain.Entity
{
    public interface IAdvertismentDetail
    {
        int TypeId { get; set; }
        bool IsActive { get; set; }
        DateTimeOffset CreatedAt { get; set; }
        DateTimeOffset UpdatedAt { get; set; }
    }
}