// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entity;

public partial class RfdtJobType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public virtual ICollection<AdvertisementJobType> AdvertisementJobTypes { get; set; } = new List<AdvertisementJobType>();

    public virtual ICollection<UserExperienceJobType> UserExperienceJobTypes { get; set; } = new List<UserExperienceJobType>();
}