// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entity;

public partial class RfdtWorkingLocation
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public virtual ICollection<AdvertismentWorkingLocation> AdvertismentWorkingLocations { get; set; } = new List<AdvertismentWorkingLocation>();

    public virtual ICollection<UserExperienceWorkingLocation> UserExperienceWorkingLocations { get; set; } = new List<UserExperienceWorkingLocation>();
}