// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entity;

public partial class UserCv
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string FileName { get; set; }

    public bool IsPublic { get; set; }

    public byte[] DataOfFile { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public virtual User User { get; set; }
}