// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entity;

public partial class UserEducation
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsPublic { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<UserEducationProfessionalBranch> UserEducationProfessionalBranches { get; set; } = new List<UserEducationProfessionalBranch>();
}