// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entity;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Username { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public byte Role { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public virtual ICollection<Advertisement> Advertisements { get; set; } = new List<Advertisement>();

    public virtual ICollection<Chat> ChatUserId1Navigations { get; set; } = new List<Chat>();

    public virtual ICollection<Chat> ChatUserId2Navigations { get; set; } = new List<Chat>();

    public virtual ICollection<ContactRequest> ContactRequestUserRequests { get; set; } = new List<ContactRequest>();

    public virtual ICollection<ContactRequest> ContactRequestUserResivers { get; set; } = new List<ContactRequest>();

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<UserCv> UserCvs { get; set; } = new List<UserCv>();

    public virtual ICollection<UserEducation> UserEducations { get; set; } = new List<UserEducation>();

    public virtual ICollection<UserExperience> UserExperiences { get; set; } = new List<UserExperience>();

    public virtual ICollection<UserPassword> UserPasswords { get; set; } = new List<UserPassword>();

    public virtual ICollection<UserPhotoProfile> UserPhotoProfiles { get; set; } = new List<UserPhotoProfile>();
}