// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entity;

public partial class UserExperience
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string FreeTxt { get; set; }

    public bool IsPublic { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public DateOnly StartedAt { get; set; }

    public DateOnly EndedAt { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<UserExperienceJobType> UserExperienceJobTypes { get; set; } = new List<UserExperienceJobType>();

    public virtual ICollection<UserExperienceWorkingLocation> UserExperienceWorkingLocations { get; set; } = new List<UserExperienceWorkingLocation>();

    public virtual ICollection<UserExpirienceProfessionalBranch> UserExpirienceProfessionalBranches { get; set; } = new List<UserExpirienceProfessionalBranch>();
}