// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YSProject.Domain.Entity;

public partial class Advertisement
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int CreatorId { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset DateCreated { get; set; }

    public DateTimeOffset DateUpdated { get; set; }

    public string FreeTxt { get; set; }

    public byte Status { get; set; }

    public virtual User Creator { get; set; }
}