// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YSProject.Domain.Entity;

public partial class Comment
{
    public int Id { get; set; }

    public int PostId { get; set; }

    public int CreatorId { get; set; }

    public string FreeTxt { get; set; }

    public DateTimeOffset CreatedId { get; set; }

    public DateTimeOffset UpdatedId { get; set; }

    public virtual User Creator { get; set; }

    public virtual Post Post { get; set; }
}