// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YSProject.Domain.Entity;

public partial class ContactRequest
{
    public int Id { get; set; }

    public int UserRequestId { get; set; }

    public int UserResiverId { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset DateCreated { get; set; }

    public DateTimeOffset DateUpdated { get; set; }

    public bool IsAccepted { get; set; }

    public virtual User UserRequest { get; set; }

    public virtual User UserResiver { get; set; }
}