// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YSProject.Domain.Entity;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string SurName { get; set; }

    public string Username { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public bool IsActive { get; set; }

    public byte Role { get; set; }

    public DateTimeOffset DateCreated { get; set; }

    public DateTimeOffset DateUpdated { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Advertisement> Advertisements { get; set; } = new List<Advertisement>();

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<ContactRequest> ContactRequestUserRequests { get; set; } = new List<ContactRequest>();

    public virtual ICollection<ContactRequest> ContactRequestUserResivers { get; set; } = new List<ContactRequest>();

    public virtual ICollection<Cv> Cvs { get; set; } = new List<Cv>();

    public virtual ICollection<Education> Educations { get; set; } = new List<Education>();

    public virtual ICollection<Experience> Experiences { get; set; } = new List<Experience>();

    public virtual ICollection<Message> MessageResivers { get; set; } = new List<Message>();

    public virtual ICollection<Message> MessageSenders { get; set; } = new List<Message>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}