// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LinkiedInWebApi.Domain.Entities;

public partial class Message
{
    public int Id { get; set; }

    public int SenderId { get; set; }

    public int ResiverId { get; set; }

    public string FreeTxt { get; set; }

    public DateTimeOffset DateCreated { get; set; }

    public DateTimeOffset DateUpdated { get; set; }

    public virtual User Resiver { get; set; }

    public virtual User Sender { get; set; }
}